import React from 'react';
import type { StyleProp, ViewStyle } from 'react-native';
import type { AudioGuidance, CameraPosition, CameraPerspective, MapType, Marker, NavigationTheme, OnArrivalEvent, OnLocationChangedEvent, OnMapClickEvent, OnNavigationStateChangedEvent, OnRemainingTimeOrDistanceChangedEvent, OnRoutePolylineEvent, OnRouteReadyEvent, OnSpeedingEvent, OnTurnByTurnUpdatedEvent, OnWaypointETAsUpdatedEvent, RoutingOptions, Waypoint } from './types';
export interface GoogleNavViewRef {
    setDestinations: (waypoints: Waypoint[], options?: RoutingOptions) => void;
    addDestination: (waypoint: Waypoint, atIndex?: number) => void;
    removeDestination: (atIndex: number) => void;
    updateDestination: (atIndex: number, waypoint: Waypoint) => void;
    startGuidance: () => void;
    stopGuidance: () => void;
    clearDestinations: () => void;
    recenterCamera: () => void;
    showRouteOverview: () => void;
    moveCamera: (position: CameraPosition) => void;
    setAudioGuidance: (guidance: AudioGuidance) => void;
    startSimulation: () => void;
    stopSimulation: () => void;
    addMarker: (marker: Marker) => void;
    removeMarker: (markerId: string) => void;
    clearMap: () => void;
    getCurrentRoute: () => Promise<OnRoutePolylineEvent>;
}
export interface GoogleNavViewProps {
    style?: StyleProp<ViewStyle>;
    mapType?: MapType;
    mapColorScheme?: number;
    compassEnabled?: boolean;
    myLocationButtonEnabled?: boolean;
    myLocationEnabled?: boolean;
    rotateGesturesEnabled?: boolean;
    scrollGesturesEnabled?: boolean;
    tiltGesturesEnabled?: boolean;
    zoomGesturesEnabled?: boolean;
    trafficEnabled?: boolean;
    buildingsEnabled?: boolean;
    indoorEnabled?: boolean;
    navigationUIEnabled?: boolean;
    headerEnabled?: boolean;
    footerEnabled?: boolean;
    tripProgressBarEnabled?: boolean;
    speedometerEnabled?: boolean;
    speedLimitIconEnabled?: boolean;
    recenterButtonEnabled?: boolean;
    trafficIncidentCardsEnabled?: boolean;
    followingPerspective?: CameraPerspective;
    theme?: NavigationTheme;
    onMapReady?: () => void;
    onMapClick?: (event: OnMapClickEvent) => void;
    onNavigationReady?: () => void;
    onRouteReady?: (event: OnRouteReadyEvent) => void;
    onArrival?: (event: OnArrivalEvent) => void;
    onLocationChanged?: (event: OnLocationChangedEvent) => void;
    onTurnByTurnUpdated?: (event: OnTurnByTurnUpdatedEvent) => void;
    onNavigationStateChanged?: (event: OnNavigationStateChangedEvent) => void;
    onRemainingTimeOrDistanceChanged?: (event: OnRemainingTimeOrDistanceChangedEvent) => void;
    onRouteChanged?: () => void;
    onTrafficUpdated?: () => void;
    onRerouting?: () => void;
    onSpeeding?: (event: OnSpeedingEvent) => void;
    onWaypointETAsUpdated?: (event: OnWaypointETAsUpdatedEvent) => void;
}
export declare const GoogleNavView: React.ForwardRefExoticComponent<GoogleNavViewProps & React.RefAttributes<GoogleNavViewRef>>;
//# sourceMappingURL=GoogleNavView.d.ts.map